Display sub-items in course sidebar
Qiskit/saiba pull request #292
Opened 2022-11-10 16:20 UTC by korgan00

## Changes

Fix https://github.com/Qiskit/saiba/issues/170

## Implementation details

Since the `walkTokens.ts` is growing. I created a new `walk-tokens` for moving all the `walkXXXX` functions in separate files.
The `RendererMarkdown` file is not used anymore in `UnitContent` since it only uses a function. Now, the function returns additional information for the application that doesn't make sense to have in it.

2022-11-14 20:40 UTC, abdonrd commented
The jump is appreciated while the titles are not finished extracting:

https://user-images.githubusercontent.com/1007051/201761183-a321255d-870d-48bc-8b06-dc99a76c2ee7.mov

Maybe we should start moving this kind of logic to the server?

2022-11-14 20:40 UTC, abdonrd approved these changes
I'm not sure about the `walkHeadings` logic, but the other looks good!

2022-11-14 20:45 UTC, abdonrd commented
Oh! Two things I just realized aren't working as expected:

- The links doesn't work; when I click in a sub-item, doesn't scroll me to the corresponding section.
- The active section is not highlighted.

2022-11-14 20:46 UTC, abdonrd requested changes
Oh! Two things I just realized aren't working as expected:

- The links doesn't work; when I click in a sub-item, doesn't scroll me to the corresponding section.
- The active section is not highlighted.

2022-11-16 21:39 UTC, yoshiemuranaka reviewed
tested locally and works great! just left one comment

2022-11-16 21:39 UTC, yoshiemuranaka commented on assets/scss/main.scss
> +  overflow-x: clip;
isn't this declaration overriding the previous line?

2022-11-17 09:48 UTC, korgan00 commented on assets/scss/main.scss
> +  overflow-x: clip;
`clip` "only" has 81% of global usage, I am using `hidden` as fallback.

2022-11-17 10:59 UTC, korgan00 commented
> Oh! Two things I just realized aren't working as expected:
> 
> * The links doesn't work; when I click in a sub-item, doesn't scroll me to the corresponding section.
> * The active section is not highlighted.

Created a new PR to solve some of these comments.
If you agree, we can merge this PR.

2022-11-17 14:32 UTC, yoshiemuranaka commented on assets/scss/main.scss
> +  overflow-x: clip;
makes sense! maybe a comment would be helpful so it isn't accidentally refactored in the future.

```
  overflow-x: hidden; // fallback
```

2022-11-17 15:15 UTC, korgan00 commented on assets/scss/main.scss
>    overflow-x: hidden;
```suggestion
  overflow-x: hidden; // fallback
```

2022-11-17 15:17 UTC, korgan00 commented on assets/scss/main.scss
> +  overflow-x: clip;
https://github.com/Qiskit/saiba/pull/292#discussion_r1025326825

2022-11-17 17:13 UTC, yoshiemuranaka approved these changes

2022-11-17 19:31 UTC, abdonrd commented
Looks like it's not working?

https://saiba-pr-292.tfb1j0wd7x2.us-south.codeengine.appdomain.cloud/course/course-aa/unit-03

<img width="1101" alt="Screenshot 2022-11-17 at 2 31 23 PM" src="https://user-images.githubusercontent.com/1007051/202541178-4569b926-13f3-42de-af0c-20a44659c735.png">

2022-11-17 20:35 UTC, abdonrd commented
Ok, it's because the h1 it's now ignored!

2022-11-17 20:36 UTC, abdonrd approved these changes

2022-11-17 22:04 UTC, merged