Store user progression in backend
Qiskit/saiba pull request #294
Opened 2022-11-11 12:11 UTC by Tansito

## Changes

Fix #189 

This PR allows to store the progression of a user in a specific unit.

## Implementation details

For this feature we created:
- Three services to: create a progression with its goal, create a goal and update a goal.
- Updated the method that sets the progression of a unit in the store.
- Updated the types of the different entities.

## How to read this PR

I would recommend to start the review from the `setUnitProgressionGoalFromWidget` method in `store\user\store.ts` and navigate through it.

In that method we just check for two things mainly:
- If the progression doesn't exist we create it.
- If the progression exists:
  - We create or update the goal.

All these actions are being supported for authenticated and non-authenticated users. The main difference between the data managed by these users are the `id` fields in those entities. For non authenticated users the progression and the goal don't have ids.

2022-11-16 12:01 UTC, y4izus requested changes
Thank you very much!! I have some comments, but mostly are related with naming :)

2022-11-16 20:29 UTC, yoshiemuranaka requested changes
Didn't test flow, but left a few code comments!

2022-11-16 20:29 UTC, yoshiemuranaka commented on store/user/store.ts
> +  function isLoggedIn() {
could this just be a computed value?

2022-11-16 20:29 UTC, yoshiemuranaka commented on services/user.ts
> +      mutation CreateProgressionGoal($unitId: String!, $customId: String!, $dateCompletedProgressions: Date = null, $dateCompletedGoals: Date = null, $additionalData: JSON = null) {
are default values needed here? Won't `null` already be the value when passed as part of mutationVariables?

2022-11-16 20:29 UTC, yoshiemuranaka commented on services/user.ts
> +          create_progressions_item(
is this a graphql function provided by directus?

2022-11-16 20:29 UTC, yoshiemuranaka commented on store/user/store.ts
> +    const goalFiltered = progression.goals.find((goal) => goal.custom_id === goalFromWidget.custom_id);
```suggestion
    const doesGoalExist = progression.goals.find((goal) => goal.custom_id === goalFromWidget.custom_id);
```

2022-11-16 20:29 UTC, yoshiemuranaka commented on store/user/store.ts
>      progression.goals = [
Not clear to me what this progression object is doing...

2022-11-17 12:57 UTC, Tansito commented on widgets/types/goal.ts
>  export interface Goal {
Done in [245c74f](https://github.com/Qiskit/saiba/pull/294/commits/245c74f61de5f7342cb9d4251e33db2ceb5c31ea) !

Something that I didn't implemented was the support to optional `additional_data?`. I was thinking about it and how we don't know yet if it's going to be optional or not I preferred to be more strict. But we can discuss if we see that it creates problems.

2022-11-17 14:24 UTC, Tansito commented on components/unit/Content.vue
> +  userStore.setUnitProgressionGoalFromWidget(activeUnitId.value, state);
Done! [f0ffb9f](https://github.com/Qiskit/saiba/pull/294/commits/f0ffb9f13ef70d1bedccdaef2bcf357eba8af1d0)

2022-11-17 15:11 UTC, Tansito commented on store/user/store.ts
> +      progression = await generateProgressionAndGoalFromWidget(unitId, goal);
Done! [aaccc25](https://github.com/Qiskit/saiba/pull/294/commits/aaccc257690930f41e0ed6a192cb68e0a9ff7bd3)

2022-11-17 15:53 UTC, Tansito commented on services/user.ts
> +      mutation CreateProgressionGoal($unitId: String!, $customId: String!, $dateCompletedProgressions: Date = null, $dateCompletedGoals: Date = null, $additionalData: JSON = null) {
I'm not sure but I will confirm it as soon as I arrive to this 👍

2022-11-17 15:57 UTC, Tansito commented on services/user.ts
> +          create_progressions_item(
<img width="317" alt="Screenshot 2022-11-17 at 16 57 26" src="https://user-images.githubusercontent.com/9059044/202495202-0c305043-5cc2-4f85-9b9d-2171c9a9b9af.png">

2022-11-17 16:07 UTC, Tansito commented on store/user/store.ts
>      progression.goals = [
The idea here is:

1. I receive in this method a `WidgetGoal` without `id` (because `widgets` don't manage `ids` if not `custom_ids`).
2. If the user doesn't have a progression I create the progression and the goal in the same call.
3. With that call I retrieve the progression and the goals of that progression.

But now that I'm explaining this to you I just see that the `find` has no sense because how I'm creating the `progression` obviously I'm going to have just one `goal` so... 😂 . As soon as I arrive to this review I will take a look more in depth haha, thanks for this @yoshiemuranaka good catch!

2022-11-17 17:09 UTC, Tansito commented on store/user/store.ts
>      progression.goals = [
Done! [bf1a3b3](https://github.com/Qiskit/saiba/pull/294/commits/bf1a3b3073bd8afab12980e54e890df9bdca08a7)

Now instead to send a `Ref` we are sending a `MaybeRef`. And with `get` we can get the `ref.value` or the `value` itself. I share a couple of links that I was looking at with @korgan00 :
- https://vueuse.org/shared/get/
- https://github.com/vueuse/vueuse/blob/main/packages/shared/get/index.ts
- https://vuejs.org/api/reactivity-utilities.html#unref

2022-11-18 13:34 UTC, Tansito commented on store/user/store.ts
> +  function isLoggedIn() {
Done in [737e248](https://github.com/Qiskit/saiba/pull/294/commits/737e2489933d2cdc29accf4bd281c6d51de32a04)

2022-11-18 13:43 UTC, Tansito commented on store/user/store.ts
> +    const goalFiltered = progression.goals.find((goal) => goal.custom_id === goalFromWidget.custom_id);
Done in [e6ce9cc](https://github.com/Qiskit/saiba/pull/294/commits/e6ce9cc33f44d339797194783bd058a369f4ecf6)

2022-11-18 15:11 UTC, Tansito commented on store/user/store.ts
>      progression.goals = [
Done in [c1efa7a](https://github.com/Qiskit/saiba/pull/294/commits/c1efa7a2e682bd52f45dfaf31a1cb9ffff3484bb)

2022-11-18 16:34 UTC, Tansito commented on store/user/utils.ts
> +  const date_completedToDate = date_completed ? new Date(date_completed) : null;
This fix covers more changes than expected. We decided to create an issue and try to solve as soon as we can:

https://github.com/Qiskit/saiba/issues/335

2022-11-18 16:47 UTC, Tansito commented on services/user.ts
> +      mutation CreateProgressionGoal($unitId: String!, $customId: String!, $dateCompletedProgressions: Date = null, $dateCompletedGoals: Date = null, $additionalData: JSON = null) {
I was taking a look into this and they seem a bit redundant, but after playing with the code I found more interesting to maintain the default values in TS. The reason is that improves the DX, when you want to use the method is telling you that it has default values in some parameters. So maybe I would remove first the default values from the query than from TS. But it's true that I see interesting to maintain those values in the query too because is specifying to the code from where that default values come so... Not a clear opinion, honestly.

I'm open to suggestions team, @yoshiemuranaka , @abdonrd, @y4izus .

2022-11-18 16:48 UTC, Tansito commented
@yoshiemuranaka @y4izus I mostly fixed all the changes that you asked for, let me know if you think there are more things to change 🙏

2022-11-21 16:54 UTC, yoshiemuranaka commented on services/user.ts
> +      mutation CreateProgressionGoal($unitId: String!, $customId: String!, $dateCompletedProgressions: Date = null, $dateCompletedGoals: Date = null, $additionalData: JSON = null) {
My preference would be adding the TS defaults for the same reason (improved DX) and removing the query defaults

2022-11-21 17:08 UTC, yoshiemuranaka reviewed
Thanks for making updates @Tansito! Sorry didn't catch these initially, but a few more requests...

2022-11-21 17:08 UTC, yoshiemuranaka commented on store/user/store.ts
> +          null
I prefer removing optional args (less code), what do you think?

```suggestion
```

2022-11-21 17:08 UTC, yoshiemuranaka commented on store/user/store.ts
> +          null
Same as 124

```suggestion
          null
```

2022-11-21 17:08 UTC, yoshiemuranaka commented on store/user/store.ts
> +      goal = progression.goals[0];
Could goals ever be undefined? 

```suggestion
      goal = progression.goals?.[0];
```

2022-11-21 23:49 UTC, abdonrd commented on services/user.ts
> +      mutation CreateProgressionGoal($unitId: String!, $customId: String!, $dateCompletedProgressions: Date = null, $dateCompletedGoals: Date = null, $additionalData: JSON = null) {
Right now I see TS errors here:

<img width="949" alt="Screenshot 2022-11-21 at 6 48 05 PM" src="https://user-images.githubusercontent.com/1007051/203180828-ea5f0db0-b56a-4f25-b58b-fb72a8874984.png">

2022-11-21 23:49 UTC, abdonrd commented on services/user.ts
> +      mutation CreateProgressionGoal($unitId: String!, $customId: String!, $dateCompletedProgressions: Date = null, $dateCompletedGoals: Date = null, $additionalData: JSON = null) {
(it also looks like this PR is not formatted with Prettier)

2022-11-22 16:18 UTC, Tansito commented on services/user.ts
> +      mutation CreateProgressionGoal($unitId: String!, $customId: String!, $dateCompletedProgressions: Date = null, $dateCompletedGoals: Date = null, $additionalData: JSON = null) {
Answering to both:

1. We can move on with that proposition @yoshiemuranaka 
2. @abdonrd tomorrow we can connect and check my configuration, those errors don't appear in my code (check if you need to wait for refresh because for example `additional_data` is a new field, maybe it's not loading everything correctly).

2022-11-22 16:20 UTC, Tansito commented on store/user/store.ts
> +      goal = progression.goals[0];
I would say not in this case because you are creating both entities at the same time, `progression` and `goal`. Must be always one and only one.

2022-11-23 12:26 UTC, Tansito commented on services/user.ts
> +      mutation CreateProgressionGoal($unitId: String!, $customId: String!, $dateCompletedProgressions: Date = null, $dateCompletedGoals: Date = null, $additionalData: JSON = null) {
Solved in [ba1197b](https://github.com/Qiskit/saiba/pull/294/commits/ba1197bc1425b0b3fc60452913745b449c54d2f3)

2022-11-23 13:14 UTC, Tansito commented on store/user/store.ts
> +  }
Done in [9650e5a](https://github.com/Qiskit/saiba/pull/294/commits/9650e5a26d528808247fbc3ac55ecbf3fede37ce)

2022-11-23 13:18 UTC, Tansito commented on store/user/store.ts
> +          null
Done in [32fdc09](https://github.com/Qiskit/saiba/pull/294/commits/32fdc09560dc1fbfa731dd98054ca14ef370ed57)

2022-11-23 13:38 UTC, Tansito commented
Changes applied @yoshiemuranaka @y4izus , let me know if you see more things, thank you as always 🙏

2022-11-23 16:28 UTC, yoshiemuranaka approved these changes
🎉 thank you!

2022-11-23 16:34 UTC, Tansito commented on types/user.ts
> +  additional_data: JSON | null;
In this case `additional_data` can only be **JSON** or **null**. If a I configure that variable as optional it can be `undefined` value that the backend will never return (if the value doesn't exist and you ask for it the backend will return you a **null**).

2022-11-24 09:51 UTC, y4izus approved these changes
Great job! thank you @Tansito !

2022-11-24 09:52 UTC, merged