Fix ts compile errors
Qiskit/saiba pull request #324
Opened 2022-11-17 14:43 UTC by y4izus

## Changes

  Closes #299 

## Implementation details

I've fixed each file on different commits. Hope this help with the review

2022-11-17 17:21 UTC, Tansito commented on store/utils.ts
> +export function filterUndefinedObjectKeys<T extends Record<string, any>>(
I touched this method in other PR and I left this method and `addObjectInfoToList` like here:

https://github.com/Qiskit/saiba/pull/294/files#diff-0794f9cb19281f2aea03d998f4c8b246f7e344bec11d64206a2e230f821e07adR10-R11

Overall I prefer this approach instead of `Record` because we are expecting an `Object` there and `Record` it's not exactly that I think, but I'm totally open to other opinions: @abdonrd , @korgan00 , @yoshiemuranaka ?

2022-11-17 17:21 UTC, Tansito commented on store/utils.ts
> +export function addObjectInfoToList<T extends Record<string, any>>(
Similar to my previous comment in `filterUndefinedObjectKeys`.

2022-11-17 20:25 UTC, abdonrd requested changes

2022-11-17 20:25 UTC, abdonrd commented on tests/widgets/components/binary/index.test.ts
> -  beforeEach(() => {
No idea about the implications of remove the `beforeEach`.

2022-11-17 20:25 UTC, abdonrd commented on store/unit/store.ts
> +    activeUnitId.value = unitBySlug(unitSlug).value?.id || '';
Is right to assign an empty value to the `activeUnitId`? Or just avoid to change the value?

```suggestion
    const unit = unitBySlug(unitSlug);
    if (unit.value) {
      activeUnitId.value = unit.value.id;
    }
```

2022-11-17 20:25 UTC, abdonrd commented on store/utils.ts
> +export function filterUndefinedObjectKeys<T extends Record<string, any>>(
I have always used [index signatures](https://www.typescriptlang.org/docs/handbook/2/objects.html#index-signatures) like `{ [key: string]: any }`, but I don't know if now `Record` is a better option.

2022-11-17 20:25 UTC, abdonrd commented on store/utils.ts
> +export function filterUndefinedObjectKeys<T extends Record<string, any>>(
https://stackoverflow.com/posts/54100359/revisions

2022-11-17 21:21 UTC, abdonrd commented
By the way, thanks for work on this! 👏🏻

2022-11-17 21:22 UTC, abdonrd commented on nuxt.config.ts
>    buildModules: ['@pinia/nuxt'],
You can merge this https://github.com/Qiskit/saiba/pull/288 instead of `main` to check it.

2022-11-21 09:04 UTC, y4izus commented on store/utils.ts
> +export function filterUndefinedObjectKeys<T extends Record<string, any>>(
I've used `Record` because [I saw it on the docs](https://www.typescriptlang.org/docs/handbook/utility-types.html#recordkeys-type), but I don't have a strong opinion here

2022-11-21 09:20 UTC, y4izus commented on tests/widgets/components/binary/index.test.ts
> -  beforeEach(() => {
I've removed because it's not needed here and it solves the problem. We can ask Randy (he did this test) if it's ok if we remove it

2022-11-21 11:08 UTC, y4izus commented on nuxt.config.ts
>    buildModules: ['@pinia/nuxt'],
I checked it executing `npm run lint:tsc`, but I'm not having this error. Maybe we can check this together to find out what is happening

2022-11-21 11:46 UTC, y4izus commented on services/course.ts
> +  ).then((res: Query<CourseListDTO>) => res.data.courses[0]);
Done in:
- https://github.com/Qiskit/saiba/pull/324/commits/fe1e8cfa548bcd21dd6b6eebdc6614ad4b851c46
- https://github.com/Qiskit/saiba/pull/324/commits/f7ce20904995859273c43545187e0a0f4849e400
- https://github.com/Qiskit/saiba/pull/324/commits/f3dce7e92a9b6a7684e2865a851126e2d3789dc9

2022-11-21 11:57 UTC, y4izus commented on store/unit/store.ts
> +    activeUnitId.value = unitBySlug(unitSlug).value?.id || '';
I think it's right assign an empty value. `''` is the default value and if we have a unit for which we don't find the `id`, I think we should have `''` instead of the previous value.
I can be wrong, so let's ask @Tansito and @korgan00 , just in case I'm missing something

2022-11-21 12:04 UTC, Tansito commented on store/unit/store.ts
> +    activeUnitId.value = unitBySlug(unitSlug).value?.id || '';
I understand why we are using the **default value** but for me it's weird that the default value is an **empty string**. I don't know if there is a reason behind but I would say `null` or `undefined` would be better values.

2022-11-21 12:11 UTC, korgan00 commented on store/utils.ts
> +export function filterUndefinedObjectKeys<T extends Record<string, any>>(
I prefer the index signatures too

2022-11-21 12:16 UTC, korgan00 commented on store/unit/store.ts
> +    activeUnitId.value = unitBySlug(unitSlug).value?.id || '';
I fine with extending type to null or undefined but I don't have strong opinions here.

2022-11-21 13:13 UTC, abdonrd commented on nuxt.config.ts
>    buildModules: ['@pinia/nuxt'],
I think it was my problem for going to change branches. Forget it!

2022-11-21 13:30 UTC, abdonrd commented on store/utils.ts
> +export function filterUndefinedObjectKeys<T extends Record<string, any>>(
Reading this I assume the index signatures fit better for this case:
https://stackoverflow.com/questions/54100025/difference-between-index-signature-and-record-for-empty-object/54100359#54100359

2022-11-22 14:12 UTC, techtolentino commented on tests/widgets/components/binary/index.test.ts
> -  beforeEach(() => {
LGTM, thank you 👏🏼

2022-11-22 14:34 UTC, y4izus commented on store/unit/store.ts
> +    activeUnitId.value = unitBySlug(unitSlug).value?.id || '';
Done https://github.com/Qiskit/saiba/pull/324/commits/714bd0c044137c2f4e3771301e923a32ec7211df

2022-11-22 17:50 UTC, Tansito approved these changes
Thanks a lot for this @y4izus 💯

2022-11-22 18:00 UTC, merged