🚧 Feature: Cohorts
Qiskit/saiba pull request #336
Opened 2022-11-18 16:51 UTC by korgan00

Fix https://github.com/Qiskit/saiba/issues/89

This PR is for merge all the other PR before merging with `main`

2022-12-21 17:06 UTC, y4izus requested changes
Thank you!! could you ask me for another review when you finish? :)

2022-12-21 17:06 UTC, y4izus commented on pages/cohort-enrollment/[enrollmentCode].vue
> +  if (cohort) {
Could we move this code inside `useLazyAsyncData`

2022-12-21 17:52 UTC, abdonrd commented on components/cohort/MembersList.vue
> +  <div class="cohort-member-list">
I think is "member list" and not "members list".

2022-12-22 08:24 UTC, y4izus commented on components/cohort/MembersList.vue
> +  <div class="cohort-member-list">
So, the component should be `MemberList` instead of `MembersList`?

2022-12-22 11:14 UTC, abdonrd commented on components/cohort/MembersList.vue
> +  <div class="cohort-member-list">
Yes, I think so!

2022-12-22 11:23 UTC, korgan00 commented on components/cohort/Display.vue
> +  const invitationsLines = props.cohort.invitations.map((email) => email);
![Captura de Pantalla 2022-12-22 a las 12 22 41](https://user-images.githubusercontent.com/4138279/209123950-adc93a37-01fa-4215-aeb3-316b301daf9b.png)

2022-12-22 11:27 UTC, korgan00 commented on pages/account/cohort/[course-id]/edit.vue
> +  <div class="teach-course-edit">
It is the course edition, de current URL probably is confusing at this point, but with the new URL it will make more sense:

- `/account/teach/course/:courseSlug/edit`: Course management (and its cohorts)

2022-12-22 13:08 UTC, korgan00 commented on components/cohort/Display.vue
> +  const invitationsLines = props.cohort.invitations.map((email) => email);
Since doing that will need to create computed variables, I just modified the csvContent function to make it more readable:

```Typescript
const { members, invitations } = props.cohort;
  const memberLines = members.map((member) => member.email);
  const invitationsLines = invitations.map((email) => email);
```

2022-12-22 13:12 UTC, korgan00 commented on components/cohort/Display.vue
> +  const invitationsLines = props.cohort.invitations.map((email) => email);
Since doing that will force us to create more computed variables, I modified the `csvContent` function to make it more readable. Also, I deleted the  `invitations.map` call because it is useless:

```Typescript
const { members, invitations } = props.cohort;
const memberLines = members.map((member) => member.email);
const content = ['e-mail', ...memberLines, ...invitations].join('\n');
```

2022-12-22 13:16 UTC, korgan00 commented on components/cohort/MembersList.vue
> +      v-for="email in invitations"
This is done to match the database naming.

2022-12-23 20:10 UTC, abdonrd commented on types/unit.ts
> +  title?: string;
Why now the title are optional?

2022-12-23 20:10 UTC, abdonrd commented on types/course.ts
> +  title?: string;
Why now the title are optional?

2022-12-27 16:33 UTC, Tansito commented on types/unit.ts
> +  title?: string;
It shouldn't, fixing it

2022-12-27 16:33 UTC, Tansito commented on types/course.ts
> +  title?: string;
It shouldn't, fixing it

2022-12-27 22:41 UTC, abdonrd commented
Looks like the list of the enrolled members are very close:

<img width="1504" alt="Screenshot 2022-12-27 at 5 41 06 PM" src="https://user-images.githubusercontent.com/1007051/209731169-1b3572d6-2f8b-4044-89bb-8d3128072455.png">

2022-12-27 23:36 UTC, abdonrd requested changes
Small comments, overall it looks great! 👏🏻

2022-12-27 23:36 UTC, abdonrd commented on pages/account/teach/course/[course-slug]/edit/index.vue
> +    courseName.value = course.title!;
```suggestion
    courseName.value = course.title;
```

I think this is not needed.

2022-12-27 23:36 UTC, abdonrd commented on services/cohort/index.ts
> +            id: currentUser.value?.id,
```suggestion
            id: currentUser.value.id,
```

@Tansito We cannot allow this. Maybe we need another check or a `!`.

2022-12-27 23:36 UTC, abdonrd commented on pages/account/teach/course/[course-slug]/edit/index.vue
> +  ).then(() => {
Please, move to async/await.

2022-12-28 11:27 UTC, Tansito commented on services/cohort/index.ts
> +            id: currentUser.value?.id,
Yeah, totally. I added a `!` because initially this function can only be called authenticated but we could add an `if` before just to ensure us.

2022-12-28 11:27 UTC, Tansito commented on pages/account/teach/course/[course-slug]/edit/index.vue
> +    courseName.value = course.title!;
Done [e7eddcc](https://github.com/Qiskit/saiba/pull/336/commits/e7eddcc6e489d2f6e553e9780e0c3ab3aefa7950)

2022-12-28 11:28 UTC, Tansito commented on services/cohort/index.ts
> +            id: currentUser.value?.id,
Done [c956ae6](https://github.com/Qiskit/saiba/pull/336/commits/c956ae664a904eafb1d08cad6358fcebf34e700b)

2022-12-28 11:39 UTC, Tansito commented on pages/account/teach/course/[course-slug]/edit/index.vue
> +  ).then(() => {
Done [31edccf](https://github.com/Qiskit/saiba/pull/336/commits/31edccf7b8715a37b8bf1f0c4f2114413f54d193)

I changed both methods: `createCohort` and `updateCohort`

2022-12-28 12:10 UTC, Tansito commented
@abdonrd solved styles with the commits:
- [c7fa8f1](https://github.com/Qiskit/saiba/pull/336/commits/c7fa8f10bfd13f4ff4e27b68dc5e324805aacb74)
- [8d865d4](https://github.com/Qiskit/saiba/pull/336/commits/8d865d4d2c0896df587e6bf609ff48909ee5e25a)

View section:
<img width="640" alt="Screenshot 2022-12-28 at 13 09 11" src="https://user-images.githubusercontent.com/9059044/209810123-844553f5-0a7e-4d6c-8c75-3fedaefc845b.png">

Edit section:
<img width="640" alt="Screenshot 2022-12-28 at 13 10 03" src="https://user-images.githubusercontent.com/9059044/209810210-1310f345-734f-4048-966e-f75deabc35df.png">

2022-12-28 12:50 UTC, abdonrd approved these changes
🎉

2022-12-28 12:53 UTC, merged