Cohort display
Qiskit/saiba pull request #341
Opened 2022-11-21 17:34 UTC by korgan00

## Changes

Fix https://github.com/Qiskit/saiba/issues/334

## How to read this PR

go to `/account/cohort/057c74fa-2efd-4a49-b245-c81bb44142a4/edit`

2022-11-21 17:39 UTC, korgan00 commented on pages/account/cohort/[course-id]/edit.vue
> +<template>
Per offline conversations, this page link should be edit instead of list.

2022-11-22 17:08 UTC, techtolentino reviewed
Very nice work @korgan00 

just leaving a few minor comments.

I'd love to review again but I won't block, since I'll be OOO the rest of the week.

2022-11-22 17:08 UTC, techtolentino commented on components/cohort/Display.vue
> +    &__list {
I'm thinking we should give this list a max-height w/ scroll for the overflow, so that we can handle cohort are lengthy. 

One reason is that without a max-height, we push the `Download List` button all the way to the bottom of the list, and there could be hundreds of members.

**quick example**


https://user-images.githubusercontent.com/6276074/203375934-37811fe0-f425-46f9-b1c6-5521ce187231.mov

2022-11-22 17:08 UTC, techtolentino commented on components/cohort/MembersList.vue
> +      <div class="cohort-member-list__item__content">{{ member.email }}</div>
this looks good 👏🏼 

![Screenshot 2022-11-22 at 9 03 33 AM](https://user-images.githubusercontent.com/6276074/203376585-946cf8a7-7c6b-42b5-bc1f-49743047d81b.png)

2022-11-22 17:08 UTC, techtolentino commented on components/cohort/MembersList.vue
> +        <IconTrashCan class="cohort-member-list__item__action__icon" />
I don't see this class being used, maybe it's safe to remove

2022-11-22 17:08 UTC, techtolentino commented on pages/account/cohort/[course-id]/edit.vue
> +    members: [
just for practicality, let's mock at least 20 users, so we can show scrollable overflow

2022-11-22 17:30 UTC, y4izus requested changes
Thank you @korgan00 !! I have some requested changes, but mostly are naming :)

2022-11-22 17:30 UTC, y4izus commented on components/cohort/Display.vue
> +const csvContent = computed(() => {
Reading the [computed property documentation](https://vuejs.org/guide/essentials/computed.html#computed-properties), it looks like computed properties are used to recalculate a value when `ref` or `reactive` properties change. I don't see here neither a `ref` nor a `reactive` property, could you double check if we need a `computed` here? or maybe we need to convert the `props.cohort` to `ref`/ `reactive`

2022-11-22 17:30 UTC, y4izus commented on components/cohort/MembersList.vue
> +import { User } from '~/types/user';
Same as before:

```suggestion
import type { User } from '@/types/user';
```

2022-11-22 17:30 UTC, y4izus commented on components/cohort/MembersList.vue
> +        v-if="editable"
I'm not completely sure of what is editable here. I think we are referring to the member, but not sure. That said, my suggestion is to use the same convention as before: `enableEditMember` or something like that

2022-11-22 17:30 UTC, y4izus commented on components/cohort/Display.vue
> +  emits('editRequest', { cohort: props.cohort });
Are we gonna have more `emits` related with `edit`? maybe we should specify what are we editing to avoid misunderstandings in the future

2022-11-22 17:30 UTC, y4izus commented on components/cohort/MembersList.vue
> +  emits('deleteRequest', { member, index });
Same as before with the `editRequest`, maybe we need to specify what are we deleting

2022-11-22 17:30 UTC, y4izus commented on types/cohort.ts
> +import { User } from './user';
```suggestion
import type { User } from './user';
```

2022-11-23 10:04 UTC, korgan00 commented on components/cohort/Display.vue
> +  emits('editRequest', { cohort: props.cohort });
This is not an edition of the cohort. This means the user has pressed the edit button, and the parent component should change to the edit view. The display component doesn't know how it will be edited (another page, component substitution...). That's why I called it `editRequest` and the thing that we want to make editable is the cohort that we are passing to the call.

2022-11-23 10:45 UTC, korgan00 commented on pages/account/cohort/[course-id]/edit.vue
> +    members: [
done with 116

2022-11-23 11:16 UTC, korgan00 commented on components/cohort/Display.vue
> +const csvContent = computed(() => {
All the props are reactive in Vue3. In this case this `csvContent` will be updated when the cohort changes but it will not be updated if the members change. Since sometimes, Vue reuse the components in v-for, I think it will be safer this way.

2022-11-23 13:11 UTC, korgan00 commented on components/cohort/Display.vue
> +      <div class="cohort-display__header__content">
I think this part is too simple to move into a component.

2022-11-23 18:04 UTC, korgan00 commented on components/cohort/MembersList.vue
> +        v-if="editable"
changed to `enableDeleteMembers`

2022-11-23 18:09 UTC, korgan00 commented on components/cohort/MembersList.vue
> +  emits('deleteRequest', { member, index });
I tried to modify the list but there is a rule to prevent it: https://eslint.vuejs.org/rules/no-mutating-props.html

2022-11-24 10:39 UTC, y4izus approved these changes
LGTM! Thank you @korgan00 !

2022-11-24 10:51 UTC, merged