feat: add public courses to mega menu
Qiskit/saiba pull request #346
Opened 2022-11-22 20:18 UTC by yoshiemuranaka

## Changes
Adds public courses to course sidebar mega menu dropdown.
Modifies the fetch public courses function to only use the query filter if the user is authenticated (the access token exists). If the user is not authenticated, the query should return all public courses. This is necessary because the 'origin' field is only available for authenticated users.

Resolves #97

**Known issues**
- We have not defined how to group Tutorials/Chapters and other learning paths in Saiba. The changes in this PR will show all public courses in the mega menu dropdown
- Clicking the course title from the megamenu dropdown will show a 404. Created an issue to handle redirects #345
- The current mega menu web components only accepts a url string so the web component will need to be updated in order to use the `NuxtLink`

## Implementation details

- Referenced mega menu dropdown [mock for data structure](https://github.com/Qiskit/web-components/blob/main/components/mega-menu-dropdown/mockData.test.ts)

## How to read this PR

- The mega menu should load for unauthenticated and authenticated users

## Screenshots

<img width="1244" alt="Screenshot 2022-11-22 at 11 48 58 AM" src="https://user-images.githubusercontent.com/8097306/203411008-d5f78d60-70d9-464d-89b1-1eb5029b7260.png">

2022-11-23 09:48 UTC, y4izus requested changes
Thank you Yoshie! I have some refactor suggestions. If you have any doubt, let me know :)

2022-11-23 09:48 UTC, y4izus commented on services/course.ts
> +export const getPublicCourses = async (
It looks like `getPublicCourses` and `getPrivateCourses` are almost the same. If we add the filters by parameters in both cases, we could reuse the code and just have one method `getCourses` (this name is an example, if you find a better name, go for it :) )

It would also be nice to get the `origin` value on the response, so we could have all our courses on our `course` variable on the store. `publicCourses` and `privateCourses` could be computed properties that filters by `origin` the `courses` list. This way, we just have to update/maintain one variable, not 3

2022-11-23 17:01 UTC, yoshiemuranaka commented on services/course.ts
> +export const getPublicCourses = async (
Chatted a bit with @y4izus 
seems like a good idea to combine `getPublicCourses` and `getPrivateCourses` 

>It would also be nice to get the origin value on the response

This may be tricky because the property is not available for unauthenticated users

>publicCourses and privateCourses could be computed properties that filters by origin the courses list. This way, we just have to update/maintain one variable, not 3

@abdonrd [suggested](https://github.com/Qiskit/saiba/pull/269#discussion_r1017221315) to filter in the query instead of using a computed value to take advantage of graphql pagination for each course type

@y4izus still discussing possible options with the team, will wait to hear the final decision before making changes here!

2022-11-29 15:36 UTC, yoshiemuranaka commented on services/course.ts
> +export const getPublicCourses = async (
Will wait until #351 before making updates

2022-11-29 15:38 UTC, yoshiemuranaka commented
This PR is not ready for review. It will be revisited after #351 after course grouping structure defined. Will put in draft mode

2023-01-03 16:57 UTC, yoshiemuranaka commented
This PR is ready for review. We still need to make backend updates to allow the grouping of different course "types" (eg summer school) but agreed during planning that we are ok to merge these changes at least to show all the public courses

2023-01-04 17:50 UTC, abdonrd requested changes
Thanks @yoshiemuranaka! Looks good!

2023-01-04 17:50 UTC, abdonrd commented on components/course-sidebar/index.vue
> +      title: { label: course.title, url: `/course/${course.slug}` },
We can avoid this link? We don't have a course page yet.

2023-01-04 17:50 UTC, abdonrd commented on components/course-sidebar/index.vue
> +const { pending: publicCoursesPending, data: publicCourses } = useLazyAsyncData(
I'm not sure we can always assume that public is `origin=qiskit`.
So I think we can change to `qiskitCourses` or `qiskitTextbookCourses`.

2023-01-04 18:05 UTC, yoshiemuranaka commented on components/course-sidebar/index.vue
> +      title: { label: course.title, url: `/course/${course.slug}` },
Resolved by https://github.com/Qiskit/saiba/pull/346/commits/600bbab48e6ee53252164c22abfe2e567ece5c42

2023-01-04 18:05 UTC, yoshiemuranaka commented on components/course-sidebar/index.vue
> +const { pending: publicCoursesPending, data: publicCourses } = useLazyAsyncData(
Resolved by https://github.com/Qiskit/saiba/pull/346/commits/600bbab48e6ee53252164c22abfe2e567ece5c42

2023-01-04 19:05 UTC, abdonrd approved these changes

2023-01-04 22:00 UTC, merged