Cohort Edit
Qiskit/saiba pull request #348
Opened 2022-11-24 12:29 UTC by korgan00

## Changes

Fix https://github.com/Qiskit/saiba/issues/333

## How to read this PR

go to `/account/cohort/057c74fa-2efd-4a49-b245-c81bb44142a4/edit`

2022-11-28 12:39 UTC, y4izus requested changes
I have some requested changes, could you ask for another review when you finish?

Thank you!!

2022-11-28 12:39 UTC, y4izus commented on components/cohort/Edit.vue
> +import { Cohort } from '~/types/cohort';
```suggestion
import type { Cohort } from '@/types/cohort';
```

2022-11-28 12:39 UTC, y4izus commented on components/cohort/Edit.vue
> +  if (addMemberInputText.value == '') {
```suggestion
  if (addMemberInputText.value === '') {
```

2022-11-28 12:39 UTC, y4izus commented on components/cohort/Edit.vue
> +const informationMessage = reactive({
Not sure if this definition is here with a reason. If not, maybe is better to have it with the rest of the variable definitions

2022-11-28 12:39 UTC, y4izus commented on components/cohort/Edit.vue
> +    emails.forEach((email) => {
```suggestion
    emails.forEach((email: string) => {
```

2022-11-28 12:39 UTC, y4izus commented on components/cohort/Edit.vue
> +    emails.forEach((email) => {
Would it make sense to use `Promise.all` instead of `for await...`?  The first one handles its input promises concurrently, while the second one, resolves them one at the time

2022-11-28 12:39 UTC, y4izus commented on components/cohort/Edit.vue
> +function testEmail(text: string) {
Maybe `isValidEmail` is more semantic than `testEmail`

2022-11-28 14:46 UTC, korgan00 commented on components/cohort/Edit.vue
> +    emails.forEach((email) => {
Since we are using some shared variables like the counters and the list of cohort members and also checking for duplicity, I prefer not to have concurrency.

2022-11-30 08:38 UTC, y4izus approved these changes
LGTM! thank you @korgan00 !

2022-11-30 09:39 UTC, merged