🚧 Cohort services
Qiskit/saiba pull request #349
Opened 2022-11-24 16:55 UTC by Tansito

🚧 The description will be completed once time the development is finished.

Services to interact with `cohorts`:
- Create
- Update
- Get: under construction

2022-11-28 14:33 UTC, y4izus requested changes
Thank you very much! some small changes and that's all :D

2022-11-28 14:33 UTC, y4izus commented on services/cohort.ts
> +import { Query } from '@/store/types';
```suggestion
import type { Query } from '@/store/types';
```

2022-11-28 14:33 UTC, y4izus commented on services/cohort.ts
> +  name: Cohort['name'],
What about passing directly the Cohort object?

2022-11-28 14:40 UTC, Tansito commented on services/cohort.ts
> +  name: Cohort['name'],
@korgan00 and me commented the same thing but we thought that would be better to create an issue and do the refactor in all the services (we are using the same approach in all the services), I don't know what you think.

2022-11-28 14:41 UTC, Tansito commented on services/cohort.ts
> +  cohortId: Cohort['id'],
Same as my previous comment.

2022-11-29 13:19 UTC, y4izus commented on services/cohort.ts
> +  name: Cohort['name'],
you're right! you already told me about that but I forget it, sorry!🤦🏽‍♀️.  I'm completely agree :D

2022-11-29 13:33 UTC, korgan00 approved these changes
LGTM, minor change

2022-11-29 13:33 UTC, korgan00 commented on store/cohort/utils.ts
> +function memberDTOToMembers(memberDTO: MemberDTO): Member {
```suggestion
function memberDTOToMember(memberDTO: MemberDTO): Member {
```

2022-11-30 11:55 UTC, Tansito commented on services/cohort.ts
> +import { Query } from '@/store/types';
Done in [308f370](https://github.com/Qiskit/saiba/pull/349/commits/308f370661b5098a5670c2663fe85202103923f8)

2022-11-30 12:02 UTC, Tansito commented on services/utils.ts
> +};
Done in [8d06fc1](https://github.com/Qiskit/saiba/pull/349/commits/8d06fc19f0e9ad34713107a7b0d0dd64f802798c)

2022-11-30 12:04 UTC, Tansito commented on store/cohort/utils.ts
> +function memberDTOToMembers(memberDTO: MemberDTO): Member {
Done in [8c48ef1](https://github.com/Qiskit/saiba/pull/349/commits/8c48ef1981c827fcbeb147110f4ce2481d471756)

2022-11-30 13:45 UTC, y4izus approved these changes

2022-11-30 13:45 UTC, merged