Cohort list
Qiskit/saiba pull request #352
Opened 2022-11-28 09:55 UTC by korgan00

## Changes

Fix https://github.com/Qiskit/saiba/issues/332

## Implementation details

Depends on https://github.com/Qiskit/saiba/pull/348

## How to read this PR

go to /account/cohort/057c74fa-2efd-4a49-b245-c81bb44142a4/edit

2022-12-01 18:43 UTC, techtolentino requested changes
This looks great overall, @korgan00 

I left a couple of minor comments.

Thank you 👏🏼

2022-12-01 18:43 UTC, techtolentino commented on components/cohort/Edit.vue
> +      <bx-btn size="md" icon-layout @click="handleSendRequest">
small comment:

the design seems to show that there should be no spacing between the buttons. Can we add a little styling to keep the button set together?


https://user-images.githubusercontent.com/6276074/205134291-e5ae55cd-3173-40a2-bdf6-02c85bfe9fe2.mov

2022-12-07 21:48 UTC, yoshiemuranaka reviewed
looks good! left a few comments

2022-12-07 21:48 UTC, yoshiemuranaka commented on components/cohort/Edit.vue
> +const informationMessage = reactive({
I think this is used for inline validation messages? could we rename to

```suggestion
const inlineValidationMessage = reactive({
```

2022-12-07 21:48 UTC, yoshiemuranaka commented on components/cohort/Edit.vue
> +
Should we consider using a validation library? might clean up a lot of these manual checks

2022-12-12 10:46 UTC, korgan00 commented on components/cohort/MembersList.vue
> +      i -
Yes, in the next PR i made a minor change in the next PR [changing `i - ` to (invitation)](https://github.com/Qiskit/saiba/pull/383/files#diff-889e6228b5198c39789a87ffa89d7aaa13a81d0d203e3000af700dc43c2f0629) and waiting for a UX approval or change.

2022-12-13 14:53 UTC, korgan00 commented on components/cohort/MembersList.vue
> +      i -
There is new UI update that will be done after closing this PR and the one connecting with services. I think we can resolve this in favor of the redesign.

2022-12-13 15:05 UTC, korgan00 commented on components/cohort/Edit.vue
> +
I was looking for form validation libraries. Vue has few recommendations and the one that I liked more is this one: [vuelidate](https://vuelidate-next.netlify.app/)
We can move this to a discussion so every dev can give their opinion.

Right now there is few checks, so I think we can delay changing this.

2022-12-13 22:23 UTC, yoshiemuranaka commented on components/cohort/Edit.vue
> +
Created #401 to track

2022-12-13 22:25 UTC, yoshiemuranaka approved these changes
ty!

2022-12-14 14:34 UTC, merged