Create the cohort-enrollment page
Qiskit/saiba pull request #387
Opened 2022-12-07 16:08 UTC by abdonrd

## Changes

Create the cohort-enrollment page.

## Implementation details

Now we have a `/cohort-enrollment/:enrollmentCode` page.
In this page we call to the Saiba API to enroll the current user in the cohort by the `enrollmentCode`.

If we get the cohort, then we redirect to the learning page.

## Screenshots

https://user-images.githubusercontent.com/1007051/206230469-eb6b353e-8c49-4a5f-b372-09b988c18626.mov

2022-12-12 21:44 UTC, abdonrd commented
@JRussellHuffman @gracelindsell maybe you want to review the design here.

Screenshots when a when a user enter an auto-enrollment cohort...

When loading:
<img width="812" alt="Screenshot 2022-12-12 at 4 44 22 PM" src="https://user-images.githubusercontent.com/1007051/207161161-46794864-8606-4a11-874b-c4b004d7e94c.png">

When does not exist or is not enabled:
<img width="814" alt="Screenshot 2022-12-12 at 4 42 12 PM" src="https://user-images.githubusercontent.com/1007051/207160825-d6308f9b-e156-4f13-ba2f-6813da44431b.png">

2022-12-12 22:12 UTC, techtolentino approved these changes
This all looks good @abdonrd 

It'd be awesome if we could somehow reuse the Error page design that @alexao8 is working on... (except maybe we can customize the CTAs to be more relevant)

Still, I'll leave that up to the Designers.

👏🏼

2022-12-12 22:25 UTC, JRussellHuffman commented
How long can we expect "When loading" to be shown? If it's only .5 seconds, it might not spending a lot of time on the design. The second one makes sense though.

Are these the only two edge cases that need designs? And is there an issue in the backlog for them? We can take care of all these blank states in one issue if you can make a github issue with all the states we should design for.

2022-12-12 22:30 UTC, abdonrd commented
> How long can we expect "When loading" to be shown? If it's only .5 seconds, it might not spending a lot of time on the design. The second one makes sense though.

Yeah, in a normal situation it should be very fast.

> Are these the only two edge cases that need designs? And is there an issue in the backlog for them? We can take care of all these blank states in one issue if you can make a github issue with all the states we should design for.

I think so.
Of course! I will create an issue.

2022-12-12 22:35 UTC, abdonrd commented
Done!
- https://github.com/Qiskit/saiba/issues/395

2022-12-13 09:25 UTC, y4izus requested changes
Thank you!!! I've requested some changes, ask me if you have any question :)

2022-12-13 09:25 UTC, y4izus commented on pages/cohort-enrollment/[enrollmentCode].vue
> +  <div class="container">
For classes, we are following a naming based on the filename. The container class should match the name of the file, so, in this case should be `cohort-enrollment`

2022-12-13 09:25 UTC, y4izus commented on pages/cohort-enrollment/[enrollmentCode].vue
> +      </div>
Do you need this nested `divs` or could we do:

```suggestion
      <div v-else>
        The cohort does not exist or you do not have access to enroll.
      </div>
```

2022-12-13 09:25 UTC, y4izus commented on pages/cohort-enrollment/[enrollmentCode].vue
> +const enrollmentCode = route.params.enrollmentCode as string;
```suggestion
const { enrollmentCode } = route.params as string;
```

2022-12-13 09:25 UTC, y4izus commented on types/cohort.ts
> +export interface CohortDTO {
We are moving (it's part of my current task) the `DTO` interfaces to the services folder. We are doing that because those interfaces will be only used when pulling data from the database.

2022-12-13 09:25 UTC, y4izus commented on services/cohort.ts
> +  return useLazyFetch<CohortDTO>(
We decided that the service will return applications types instead of `DTO` types. 

I know that right now, the code follow what you did, so you can change it to match the new structure or we can commit this and change it in the task I'm doing. If you chose the second option, please, add a `TODO`, to make the changes easier in the future :)

2022-12-13 09:25 UTC, y4izus commented on services/cohort.ts
> +export const cohortEnrollment = (enrollmentCode: string) => {
This is a function, so it should follow the naming starting with a verb. Example: `getCohortEnrollmentCode` (it's just an example, if you find a better name, go for it :) )

2022-12-13 09:25 UTC, y4izus commented on services/cohort.ts
> +      method: 'POST',
I think you can reuse the [`gqlQueryOptions` ](https://github.com/Qiskit/saiba/blob/main/services/utils.ts#L11) here, could you check it?

2022-12-13 12:08 UTC, abdonrd commented on pages/cohort-enrollment/[enrollmentCode].vue
> +      </div>
We can do that!

2022-12-13 12:08 UTC, abdonrd commented on pages/cohort-enrollment/[enrollmentCode].vue
> +const enrollmentCode = route.params.enrollmentCode as string;
That does not work. You would be typing `params` instead of `enrollmentCode`.

2022-12-13 12:09 UTC, abdonrd commented on types/cohort.ts
> +export interface CohortDTO {
Ok!

2022-12-13 12:09 UTC, abdonrd commented on services/cohort.ts
> +      method: 'POST',
We don't use query, variables, etc. In fact we do not send anything for the body.

2022-12-13 12:11 UTC, abdonrd commented on services/cohort.ts
> +export const cohortEnrollment = (enrollmentCode: string) => {
I assume the verb would be enroll; `enrollCohort`? `enrollUserInACohort`?

2022-12-13 18:06 UTC, abdonrd commented on services/cohort.ts
> +  return useLazyFetch<CohortDTO>(
Updated!

2022-12-14 08:35 UTC, y4izus commented on pages/cohort-enrollment/[enrollmentCode].vue
> +  <div class="container">
There is no a strong reason, we thought that would be more readable and we continued naming the classes like this. We can open a discussion to check again with the team which option they prefer :)

2022-12-14 08:37 UTC, y4izus commented on pages/cohort-enrollment/[enrollmentCode].vue
> +const enrollmentCode = route.params.enrollmentCode as string;
You're right! I didn't realize we have the `as string`, sorry

2022-12-14 08:42 UTC, y4izus commented on services/cohort.ts
> +      method: 'POST',
But the `gqlQueryOptions` also adds the access token to the header and add the `method: 'POST'` and so on. Maybe we can extract that basic configuration to a new function and reuse it in both, your code and the `gqlQueryOptions` function

2022-12-14 08:50 UTC, y4izus commented on services/cohort.ts
> +export const cohortEnrollment = (enrollmentCode: string) => {
I like the `enrollUserInACohort` option :) , I think it's more readable

2022-12-14 13:08 UTC, abdonrd commented on services/cohort.ts
> +      method: 'POST',
Updated with the `apiRestOptions` util!

2022-12-14 14:12 UTC, y4izus approved these changes
LGTM!!! thank you very much @abdonrd !!

2022-12-14 14:19 UTC, merged