feat: disable unit next button and sidebar links
Qiskit/saiba pull request #416
Opened 2022-12-20 21:07 UTC by yoshiemuranaka

## Changes
Adds disabled visual states and disabled button and link functionality for unit pagination and course sidebar progression.

This PR does not cover blocking the actual path if url is manually entered (#386) 

## Implementation details
- The sidebar links and next button are disabled if the course has flow control enabled _**and**_ the Progression date_completed field is null. The `date_completed` field is currently always null, we do not have code in place that sets this Progression field value. This functionality will be completed in a separate PR

## How to read this PR
In the backend staging environment, `Quantum machine learning` has flow control enabled. To view the course and test this functionality, make sure your account is added to the `Accelerator-Test` cohort

## Screenshots

https://user-images.githubusercontent.com/8097306/208765451-a40e03ad-a984-4083-bc24-0c83dac5c78c.mov

2022-12-21 13:59 UTC, Tansito commented on store/course/store.ts
> +  function isUnitDisabled(unit: Unit) {
This is something very personal so I'm totally open to maintain the current code but for readability I usually prefer to check if something is enabled than disabled. For example in this case:

```
function isUnitEnable(unit: Unit) {
  ...
    return activeCourse.value?.flow_control && progression?.date_completed;
  ...
}
```

The generated code from my point of view is easier to read. And if you want to check the value:

```
if(!enabled) vs if(!disabled)
```
Usually for me it's easier to understand `not enabled` than `not disabled`. But as I said, a very personal opinion.

2022-12-21 14:01 UTC, Tansito commented on components/BasicLink.global.vue
> +.basic-link.disabled {
Related with #403 discussion I would like to know @korgan00's opinion here because I have the feeling that probably we should name this state in a different way.

2022-12-21 15:21 UTC, yoshiemuranaka commented on store/course/store.ts
> +  function isUnitDisabled(unit: Unit) {
Made these changes, thes only place that readability may not be improved is for the `<BasicLink>` component since we are checking for the prop `:disabled` we have to check for !enabled. hope that makes sense!

2022-12-21 15:22 UTC, yoshiemuranaka commented on components/BasicLink.global.vue
> +.basic-link.disabled {
I updated to use BEM naming. Let me know if this is ok @korgan00 @Tansito

2022-12-21 16:07 UTC, Tansito commented on store/course/store.ts
> +  function isUnitDisabled(unit: Unit) {
Yeah, I think it's ok. Thank you @yoshiemuranaka you are awesome!

2022-12-22 15:56 UTC, techtolentino requested changes
This is awesome @yoshiemuranaka 

just two small suggestions... 

🔥

2022-12-22 17:18 UTC, yoshiemuranaka commented on components/BasicLink.global.vue
> +    color: carbon.$text-disabled !important;
I updated the disabled link color in the sidebar. Since the BasicLink is global, we probably want to maintain the default lighter color (works against white bg). For the sidebar specifically where the bg is a lighter gray, I updated to use cool-gray-60. 
I'm also kind of surprised it's flagged by a11y checker...I thought disabled elements didn't adhere to the same contrast rules. It may be because it is wrapped in a span vs a form element 🤔 

Either way updated here https://github.com/Qiskit/saiba/pull/416/commits/632bdf576cdebe553280dd184ae90c912c5f7b99

2022-12-22 17:19 UTC, yoshiemuranaka commented on components/BasicLink.global.vue
> +  &--disabled {
Cool trick 👀 new to me!
I updated here https://github.com/Qiskit/saiba/pull/416/commits/632bdf576cdebe553280dd184ae90c912c5f7b99

But still needed the important to override the hover state specificity

2022-12-22 17:27 UTC, yoshiemuranaka commented on components/BasicLink.global.vue
> +  &--disabled {
Also removed !important in favor hover selector https://github.com/Qiskit/saiba/pull/416/commits/331bb1e342263e7462bec2daf9166ac7b0a83d17

2022-12-22 18:19 UTC, techtolentino approved these changes
LGTM 👏🏼

2022-12-22 18:25 UTC, merged