Refactor learning page
Qiskit/saiba pull request #421
Opened 2022-12-22 16:36 UTC by y4izus

## Changes

Part of #351 

This PR refactors the learning page (`/account/learning`) by moving to the components the logic that we don't need on the store

## Implementation details

Apart from removing code from the store, this PR also extracts code to remove duplicity:
- creates one component for the courses that are in cards
- creates one function on the service that serves for both public and private courses

## How to read this PR

- go to the `/account/learning` and checks that everything is working as expected
- check the code to see if we can improve it

2022-12-23 19:19 UTC, abdonrd commented
After this, the Unit Store is practically not used.
We have the `units` and the `activeUnit`...
But now no one ever fills the `units` array, so...
https://github.com/Qiskit/saiba/blob/12a078d3684496d699089e52c077c36ef87f2af1/widgets/components/checkbox/index.vue#L25
https://github.com/Qiskit/saiba/blob/12a078d3684496d699089e52c077c36ef87f2af1/store/user/store.ts#L93
It will stop working.

2022-12-23 19:24 UTC, abdonrd commented
Merge both courses services looks good!

2022-12-23 19:34 UTC, abdonrd commented on components/CourseCardGrid.vue
> +}
We have something from the design team?

2022-12-27 08:40 UTC, y4izus commented on components/CourseCardGrid.vue
> +}
no yet, we have to ask them for a default image

2022-12-27 10:41 UTC, y4izus commented
> After this PR, the Unit Store is practically not used. We have the `units` and the `activeUnit`... But now no one ever fills the `units` array, so these will stop working:
> 
> https://github.com/Qiskit/saiba/blob/12a078d3684496d699089e52c077c36ef87f2af1/widgets/components/checkbox/index.vue#L25
> 
> 
> https://github.com/Qiskit/saiba/blob/12a078d3684496d699089e52c077c36ef87f2af1/store/user/store.ts#L93

I think the first case will work. It uses the `activeUnitId` and that is filled on the `[unit].vue` file

For the second case, I have removed the code that is not used anymore and I have created a new function on the course store to replace the line you mentioned. Done in 91ce3a5ca49e06a428ead5a8128467aebfc0811c

2022-12-27 17:33 UTC, abdonrd requested changes
A few small changes, but in general I see it well! 👏🏻

2022-12-27 17:33 UTC, abdonrd commented on components/CourseCardGrid.vue
> +): string | null {
```suggestion
) {
```

We don't need to write the types, TypeScript can inherit it.

2022-12-27 17:33 UTC, abdonrd commented on components/CourseCardGrid.vue
> +  courseSlug: string | undefined,
```suggestion
  courseSlug: string,
```

`courseSlug` cannot be undefined.

2022-12-27 17:33 UTC, abdonrd commented on components/CourseCardGrid.vue
> +}
```suggestion
function getCardLink(courseSlug: string, courseUnits: Unit[]) {
  const firstUnitSlug = courseUnits[0].slug;

  return `/course/${courseSlug}/${firstUnitSlug}`;
}
```

I think we should assume that the course has at least one unit. Otherwise it shouldn't be published.

2022-12-27 17:33 UTC, abdonrd commented on components/MediaCard.vue
> +    cardLink?: string | null;
With X we can rever this.

2022-12-27 17:33 UTC, abdonrd commented on components/learning/PublicContent.vue
> +  publicCourses: Course[];
In this context, I think we can simply call it `courses`.

2022-12-27 17:33 UTC, abdonrd commented on components/teach/Courses.vue
> +    <CourseCardGrid :courses="courses || []" />
```suggestion
    <CourseCardGrid :courses="courses" />
```

`courses` is already an empty array by default in the `store/course/store.ts`

2022-12-28 16:02 UTC, y4izus commented on components/CourseCardGrid.vue
> +  courseSlug: string | undefined,
Done with https://github.com/Qiskit/saiba/pull/421#discussion_r1057808497

2022-12-28 16:02 UTC, y4izus commented on components/CourseCardGrid.vue
> +): string | null {
Done with https://github.com/Qiskit/saiba/pull/421#discussion_r1057808497

2022-12-28 16:10 UTC, y4izus commented on components/learning/PublicContent.vue
> +  publicCourses: Course[];
Done ff9616cbe4b72794188062881c4fc05ab6578a64

2022-12-28 16:15 UTC, y4izus commented on components/MediaCard.vue
> +    cardLink?: string | null;
Done 5554305034e78b14b482efeb961422f8546f4194

2022-12-28 20:00 UTC, abdonrd commented on components/teach/Courses.vue
> -        :card-link="`/account/teach/course/${course.slug}/edit`"
We have lost the edit link.

2022-12-29 08:58 UTC, y4izus commented on components/teach/Courses.vue
> -        :card-link="`/account/teach/course/${course.slug}/edit`"
Fixed https://github.com/Qiskit/saiba/pull/421/commits/3968ec1e3e5d71f7600501bf8402e7a3058cda5d

2022-12-29 13:53 UTC, abdonrd approved these changes
Thanks @y4izus! 👏🏻

2022-12-29 13:59 UTC, merged

2023-01-03 14:31 UTC, abdonrd commented on components/CourseCardGrid.vue
> +}
I just created a new issue: https://github.com/Qiskit/saiba/issues/441